baseURL = "/"
languageCode = "en-us"
title = "Ogden Studios"
theme = "hugo-resume"

[params]
    firstName = "Ogden"
    lastName = "Studios"
    address = "Denver, CO"
    phone = "203-695-3299"
    contactNote = "Web Design and Development"
    profileImage = "img/TechChat.png"
    email = "tyler@ogdenstudios.xyz"
    description = "We build practical solutions for pragmatic people."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/tylerwilliamsct/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/ogdenstudios/"

[params.google.analytics]
    trackerID = "UA-82629571-2"
