# Site settings

baseurl = "https://ogdenstudios.xyz/"
languageCode = "en-us"
title = "Ogden Studios"

[params]

    name = "Ogden Studios"
    description = "We build practical solutions for pragmatic people."

    # Custom assets
    custom_css = ['css/custom.css']
    custom_js  = []

    [params.navigation]
        brand = "Ogden Studios"

    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "ogden-transparent.png"
        name = "Ogden Studios"
        subtitle = "We build practical solutions for pragmatic people."

    [params.about]
        title = "What We Do"
        # The about text is splitted into a left and right column
        left = "You need a website that works. No fancy bells and whistles. Just solutions. Contact us for a free consultation."
        right = ""

      [params.footer.social]
          title = "Around the web"
          # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
          # for more icons. The icons are represented by their corresponding
          # CSS class.
          [[params.footer.social.networks]]
              icon = "fa-github"
              link = "//github.com/ogdenstudios"

          [[params.footer.social.networks]]
              icon = "fa-twitter"
              link=  "//twitter.com/ogdenstudios"

            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link=  "//facebook.com/ogdenstudios"

[[menu.main]]
  name = "Portfolio"
  weight = 100
  identifier = "portfolio"
  url = "/portfolio/"
[[menu.main]]
  name = "Pricing"
  identifier = "pricing"
  weight = 200
  url = "/pricing/"
[[menu.main]]
  name = "Blog"
  identifier = "blog"
  weight = 300
  url = "/blog/"
