# Site settings
baseurl = "https://ogdenstudios.xyz/"
languageCode = "en-us"
title = "Ogden Studios"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Ogden Studios"
    description = "We build practical solutions for pragmatic people."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "tyler@ogdenstudios.xyz"

    # Custom assets
	custom_css = ['css/custom.css']
	custom_js  = []

    [params.navigation]
        brand = "Ogden Studios"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "OgdenLogo.jpg"
        name = "Ogden Studios"
        subtitle = "We build practical solutions for pragmatic people."


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "What We Do"
        # The about text is splitted into a left and right column
        left = "You need a website that works. No fancy bells and whistles. Just solutions. We can do that. Contact us for a free consultation."
        right = ""

    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/ogdenstudios"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/ogdenstudios"

              [[params.footer.social.networks]]
                  icon = "fa-facebook"
                  link=  "//facebook.com/ogdenstudios"
